# Generated by Django 4.2.3 on 2023-07-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='appetizer',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='cuisine',
            old_name='american',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='menu_items',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu_items',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='category',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_dish',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='asian',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='mexican',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuisine',
            name='cuisine',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
