# Generated by Django 4.2.3 on 2023-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_remove_category_category_remove_cuisine_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='description',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
